server:
  port: 8765

spring:
  profiles: default, test

  datasource:
    url: jdbc:h2:mem:pissouri-db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    maxPoolSize: 8
    connectTimeout: 1800

  jpa:
    open-in-view: false

  flyway:
    locations:
      filesystem: db/migration/schema,db/migration/bootstrap

  resources:
    add-mappings: false
  mvc:
    favicon:
      enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main:
    banner-mode: "off"